WINDOW_W = 800
WINDOW_H = 600

WINDOW_BACK_SRC = "data/back.png"

BALL_MASS = 1
BALL_POWER = 2.2
BALL_RADIUS = 15
BALL_IMG_SRC = "data/ball.png"

SEGMENT_COLOR = [0, 0, 0]
SEGMENT_WIDTH = 1

FORCE_IMG_SRC = "data/force.png"
FORCE_BASE_LEN = 30
FORCE_DIST_DELTA = 3

BASKET_IMG_SRC = "data/basket.png"
BASKET_TOP_LEN = 60
BASKET_BOTOOM_LEN = 40
BASKET_HEIGHT = 40
BASKET_DELTA = 3

SPACE_GRAVITY = -1000
LEVEL_SIM_SPEED = 0.5

UI_BTN_SRC = "data/button.png"
UI_BTN_FONT = 18
UI_MOVER_SRC = "data/mover.png"
UI_POWER_FONT = 15
UI_POWER_DELTA = 30

GAME_LEVELS_PATH = "data/levels"

